### PR TITLE
Restored the serializer.

### LINKED ISSUE #5: Serialization performance
Tagging you in @VDKA !

Now that we've adopted an `indirect enum` I'm seeing some weird discrepancies with serialization performance.

`JSONSerializer` with `indirect enum` => 18 seconds
`JSONSerializer` with old enum => 5 seconds
New serializer with `indirect enum` => 10 seconds

I'm not entirely sure where the performance gap is coming from but we really need to find a way to bring this back down to the 5 second range. JSONCore is all about performance!

### PR DESCRIPTION
**Pull request by vdka**
renamed `jsonString()` -> `serialized()` this now passes through to the old JSONSerializer

Closes #5

### CODE REVIEW

**Comment by tyrone-sudeium** [comment]
I'm not sure it does close #5 actually, I tried something similar to this myself on Saturday night and the performance was only 18 seconds, versus the 5 seconds I get when running the test against tag 1.0.0 -- which leads me to believe the differential comes from the indirection layer the compiler introduces when using `indirect`.

I like the new naming scheme though, is it possible to keep all the work you did with `Optional` and the naming, but return to a non indirect enum?

**Comment by vdka** [comment]
Check the commit `indirect` has been removed, essentially now, the changes from `1.0.0` just include renaming and expansion of functionality.

**Comment by tyrone-sudeium** [comment]
Oh cool, I saw that it still had `JSON` inside the enum itself for object and array and I thought that only worked if it was indirect. I stand corrected. Will verify performance and whatnot tonight!

**Comment by vdka** [comment]
I thought that too, not sure how it works without it.

**Comment by tyrone-sudeium** [comment]
Weird, I'm trying to compile this code in Xcode 7.2.1 in Release mode and the compiler is infinite looping... Will see if I can work around.

**Pull request merged**
