### PR TITLE
Made compatible with Swift Package Manager

### PR DESCRIPTION
**Pull request by vdka**
Note that a semantic tag will be required for compatibility with Swift Package Manager and the tag should also provide compatibility for Carthage.

### CODE REVIEW

**Comment by tyrone-sudeium** [comment]
This is great, I was just about to get around to this myself! Only one note, there's a typo in the README.md,

`name: "HellowWorld",` should probably be `name: "HelloWorld",`

As for the semantic tag, this'll go 1.0.0 once there's a working pretty printer (and corresponding tests) for the serializer.

**Comment by tyrone-sudeium** [comment]
@VDKA Pretty printer done, just about ready for 1.0.0. Fix those merge conflicts and we'll be good to go!

**Comment by vdka** [comment]
Ready to go, @tyrone-sudeium

**Comment by vdka** [comment]
@tyrone-sudeium Just reminding you to add the tag.

**Comment by tyrone-sudeium** [comment]
@VDKA Yep, after Star Wars :)

**Pull request merged**
